import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bg = "bg-gray-600 bg-linear-to-t from-teal-900 via-teal-600";
const color = "text-white";
const position =
  "flex items-center justify-center h-full w-full mx-auto min-h-dvh";

export const metadata: Metadata = {
  title: "Jesus Miranda - NextJs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${bg} ${color} ${position}`}
      >
        {children}
      </body>
    </html>
  );
}
